services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
    - "5000:5000"

  frontend:
    build: ./client
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
